// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/agentgroupdelegation"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// AgentGroupDelegationUpdate is the builder for updating AgentGroupDelegation entities.
type AgentGroupDelegationUpdate struct {
	config
	hooks    []Hook
	mutation *AgentGroupDelegationMutation
}

// Where appends a list predicates to the AgentGroupDelegationUpdate builder.
func (_u *AgentGroupDelegationUpdate) Where(ps ...predicate.AgentGroupDelegation) *AgentGroupDelegationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AgentGroupDelegationUpdate) SetUpdatedAt(v time.Time) *AgentGroupDelegationUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *AgentGroupDelegationUpdate) SetDeletedAt(v time.Time) *AgentGroupDelegationUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *AgentGroupDelegationUpdate) SetNillableDeletedAt(v *time.Time) *AgentGroupDelegationUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *AgentGroupDelegationUpdate) ClearDeletedAt() *AgentGroupDelegationUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetManagerUserID sets the "manager_user_id" field.
func (_u *AgentGroupDelegationUpdate) SetManagerUserID(v int64) *AgentGroupDelegationUpdate {
	_u.mutation.SetManagerUserID(v)
	return _u
}

// SetNillableManagerUserID sets the "manager_user_id" field if the given value is not nil.
func (_u *AgentGroupDelegationUpdate) SetNillableManagerUserID(v *int64) *AgentGroupDelegationUpdate {
	if v != nil {
		_u.SetManagerUserID(*v)
	}
	return _u
}

// SetChildUserID sets the "child_user_id" field.
func (_u *AgentGroupDelegationUpdate) SetChildUserID(v int64) *AgentGroupDelegationUpdate {
	_u.mutation.SetChildUserID(v)
	return _u
}

// SetNillableChildUserID sets the "child_user_id" field if the given value is not nil.
func (_u *AgentGroupDelegationUpdate) SetNillableChildUserID(v *int64) *AgentGroupDelegationUpdate {
	if v != nil {
		_u.SetChildUserID(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *AgentGroupDelegationUpdate) SetGroupID(v int64) *AgentGroupDelegationUpdate {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *AgentGroupDelegationUpdate) SetNillableGroupID(v *int64) *AgentGroupDelegationUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetRateMultiplier sets the "rate_multiplier" field.
func (_u *AgentGroupDelegationUpdate) SetRateMultiplier(v float64) *AgentGroupDelegationUpdate {
	_u.mutation.ResetRateMultiplier()
	_u.mutation.SetRateMultiplier(v)
	return _u
}

// SetNillableRateMultiplier sets the "rate_multiplier" field if the given value is not nil.
func (_u *AgentGroupDelegationUpdate) SetNillableRateMultiplier(v *float64) *AgentGroupDelegationUpdate {
	if v != nil {
		_u.SetRateMultiplier(*v)
	}
	return _u
}

// AddRateMultiplier adds value to the "rate_multiplier" field.
func (_u *AgentGroupDelegationUpdate) AddRateMultiplier(v float64) *AgentGroupDelegationUpdate {
	_u.mutation.AddRateMultiplier(v)
	return _u
}

// SetCanDelegate sets the "can_delegate" field.
func (_u *AgentGroupDelegationUpdate) SetCanDelegate(v bool) *AgentGroupDelegationUpdate {
	_u.mutation.SetCanDelegate(v)
	return _u
}

// SetNillableCanDelegate sets the "can_delegate" field if the given value is not nil.
func (_u *AgentGroupDelegationUpdate) SetNillableCanDelegate(v *bool) *AgentGroupDelegationUpdate {
	if v != nil {
		_u.SetCanDelegate(*v)
	}
	return _u
}

// SetManagerID sets the "manager" edge to the User entity by ID.
func (_u *AgentGroupDelegationUpdate) SetManagerID(id int64) *AgentGroupDelegationUpdate {
	_u.mutation.SetManagerID(id)
	return _u
}

// SetManager sets the "manager" edge to the User entity.
func (_u *AgentGroupDelegationUpdate) SetManager(v *User) *AgentGroupDelegationUpdate {
	return _u.SetManagerID(v.ID)
}

// SetChildID sets the "child" edge to the User entity by ID.
func (_u *AgentGroupDelegationUpdate) SetChildID(id int64) *AgentGroupDelegationUpdate {
	_u.mutation.SetChildID(id)
	return _u
}

// SetChild sets the "child" edge to the User entity.
func (_u *AgentGroupDelegationUpdate) SetChild(v *User) *AgentGroupDelegationUpdate {
	return _u.SetChildID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *AgentGroupDelegationUpdate) SetGroup(v *Group) *AgentGroupDelegationUpdate {
	return _u.SetGroupID(v.ID)
}

// Mutation returns the AgentGroupDelegationMutation object of the builder.
func (_u *AgentGroupDelegationUpdate) Mutation() *AgentGroupDelegationMutation {
	return _u.mutation
}

// ClearManager clears the "manager" edge to the User entity.
func (_u *AgentGroupDelegationUpdate) ClearManager() *AgentGroupDelegationUpdate {
	_u.mutation.ClearManager()
	return _u
}

// ClearChild clears the "child" edge to the User entity.
func (_u *AgentGroupDelegationUpdate) ClearChild() *AgentGroupDelegationUpdate {
	_u.mutation.ClearChild()
	return _u
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *AgentGroupDelegationUpdate) ClearGroup() *AgentGroupDelegationUpdate {
	_u.mutation.ClearGroup()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AgentGroupDelegationUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AgentGroupDelegationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AgentGroupDelegationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AgentGroupDelegationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AgentGroupDelegationUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if agentgroupdelegation.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized agentgroupdelegation.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := agentgroupdelegation.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *AgentGroupDelegationUpdate) check() error {
	if _u.mutation.ManagerCleared() && len(_u.mutation.ManagerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AgentGroupDelegation.manager"`)
	}
	if _u.mutation.ChildCleared() && len(_u.mutation.ChildIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AgentGroupDelegation.child"`)
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AgentGroupDelegation.group"`)
	}
	return nil
}

func (_u *AgentGroupDelegationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(agentgroupdelegation.Table, agentgroupdelegation.Columns, sqlgraph.NewFieldSpec(agentgroupdelegation.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(agentgroupdelegation.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(agentgroupdelegation.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(agentgroupdelegation.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RateMultiplier(); ok {
		_spec.SetField(agentgroupdelegation.FieldRateMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRateMultiplier(); ok {
		_spec.AddField(agentgroupdelegation.FieldRateMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CanDelegate(); ok {
		_spec.SetField(agentgroupdelegation.FieldCanDelegate, field.TypeBool, value)
	}
	if _u.mutation.ManagerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentgroupdelegation.ManagerTable,
			Columns: []string{agentgroupdelegation.ManagerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ManagerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentgroupdelegation.ManagerTable,
			Columns: []string{agentgroupdelegation.ManagerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChildCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentgroupdelegation.ChildTable,
			Columns: []string{agentgroupdelegation.ChildColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChildIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentgroupdelegation.ChildTable,
			Columns: []string{agentgroupdelegation.ChildColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentgroupdelegation.GroupTable,
			Columns: []string{agentgroupdelegation.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentgroupdelegation.GroupTable,
			Columns: []string{agentgroupdelegation.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{agentgroupdelegation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AgentGroupDelegationUpdateOne is the builder for updating a single AgentGroupDelegation entity.
type AgentGroupDelegationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AgentGroupDelegationMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AgentGroupDelegationUpdateOne) SetUpdatedAt(v time.Time) *AgentGroupDelegationUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *AgentGroupDelegationUpdateOne) SetDeletedAt(v time.Time) *AgentGroupDelegationUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *AgentGroupDelegationUpdateOne) SetNillableDeletedAt(v *time.Time) *AgentGroupDelegationUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *AgentGroupDelegationUpdateOne) ClearDeletedAt() *AgentGroupDelegationUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetManagerUserID sets the "manager_user_id" field.
func (_u *AgentGroupDelegationUpdateOne) SetManagerUserID(v int64) *AgentGroupDelegationUpdateOne {
	_u.mutation.SetManagerUserID(v)
	return _u
}

// SetNillableManagerUserID sets the "manager_user_id" field if the given value is not nil.
func (_u *AgentGroupDelegationUpdateOne) SetNillableManagerUserID(v *int64) *AgentGroupDelegationUpdateOne {
	if v != nil {
		_u.SetManagerUserID(*v)
	}
	return _u
}

// SetChildUserID sets the "child_user_id" field.
func (_u *AgentGroupDelegationUpdateOne) SetChildUserID(v int64) *AgentGroupDelegationUpdateOne {
	_u.mutation.SetChildUserID(v)
	return _u
}

// SetNillableChildUserID sets the "child_user_id" field if the given value is not nil.
func (_u *AgentGroupDelegationUpdateOne) SetNillableChildUserID(v *int64) *AgentGroupDelegationUpdateOne {
	if v != nil {
		_u.SetChildUserID(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *AgentGroupDelegationUpdateOne) SetGroupID(v int64) *AgentGroupDelegationUpdateOne {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *AgentGroupDelegationUpdateOne) SetNillableGroupID(v *int64) *AgentGroupDelegationUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetRateMultiplier sets the "rate_multiplier" field.
func (_u *AgentGroupDelegationUpdateOne) SetRateMultiplier(v float64) *AgentGroupDelegationUpdateOne {
	_u.mutation.ResetRateMultiplier()
	_u.mutation.SetRateMultiplier(v)
	return _u
}

// SetNillableRateMultiplier sets the "rate_multiplier" field if the given value is not nil.
func (_u *AgentGroupDelegationUpdateOne) SetNillableRateMultiplier(v *float64) *AgentGroupDelegationUpdateOne {
	if v != nil {
		_u.SetRateMultiplier(*v)
	}
	return _u
}

// AddRateMultiplier adds value to the "rate_multiplier" field.
func (_u *AgentGroupDelegationUpdateOne) AddRateMultiplier(v float64) *AgentGroupDelegationUpdateOne {
	_u.mutation.AddRateMultiplier(v)
	return _u
}

// SetCanDelegate sets the "can_delegate" field.
func (_u *AgentGroupDelegationUpdateOne) SetCanDelegate(v bool) *AgentGroupDelegationUpdateOne {
	_u.mutation.SetCanDelegate(v)
	return _u
}

// SetNillableCanDelegate sets the "can_delegate" field if the given value is not nil.
func (_u *AgentGroupDelegationUpdateOne) SetNillableCanDelegate(v *bool) *AgentGroupDelegationUpdateOne {
	if v != nil {
		_u.SetCanDelegate(*v)
	}
	return _u
}

// SetManagerID sets the "manager" edge to the User entity by ID.
func (_u *AgentGroupDelegationUpdateOne) SetManagerID(id int64) *AgentGroupDelegationUpdateOne {
	_u.mutation.SetManagerID(id)
	return _u
}

// SetManager sets the "manager" edge to the User entity.
func (_u *AgentGroupDelegationUpdateOne) SetManager(v *User) *AgentGroupDelegationUpdateOne {
	return _u.SetManagerID(v.ID)
}

// SetChildID sets the "child" edge to the User entity by ID.
func (_u *AgentGroupDelegationUpdateOne) SetChildID(id int64) *AgentGroupDelegationUpdateOne {
	_u.mutation.SetChildID(id)
	return _u
}

// SetChild sets the "child" edge to the User entity.
func (_u *AgentGroupDelegationUpdateOne) SetChild(v *User) *AgentGroupDelegationUpdateOne {
	return _u.SetChildID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *AgentGroupDelegationUpdateOne) SetGroup(v *Group) *AgentGroupDelegationUpdateOne {
	return _u.SetGroupID(v.ID)
}

// Mutation returns the AgentGroupDelegationMutation object of the builder.
func (_u *AgentGroupDelegationUpdateOne) Mutation() *AgentGroupDelegationMutation {
	return _u.mutation
}

// ClearManager clears the "manager" edge to the User entity.
func (_u *AgentGroupDelegationUpdateOne) ClearManager() *AgentGroupDelegationUpdateOne {
	_u.mutation.ClearManager()
	return _u
}

// ClearChild clears the "child" edge to the User entity.
func (_u *AgentGroupDelegationUpdateOne) ClearChild() *AgentGroupDelegationUpdateOne {
	_u.mutation.ClearChild()
	return _u
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *AgentGroupDelegationUpdateOne) ClearGroup() *AgentGroupDelegationUpdateOne {
	_u.mutation.ClearGroup()
	return _u
}

// Where appends a list predicates to the AgentGroupDelegationUpdate builder.
func (_u *AgentGroupDelegationUpdateOne) Where(ps ...predicate.AgentGroupDelegation) *AgentGroupDelegationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AgentGroupDelegationUpdateOne) Select(field string, fields ...string) *AgentGroupDelegationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AgentGroupDelegation entity.
func (_u *AgentGroupDelegationUpdateOne) Save(ctx context.Context) (*AgentGroupDelegation, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AgentGroupDelegationUpdateOne) SaveX(ctx context.Context) *AgentGroupDelegation {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AgentGroupDelegationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AgentGroupDelegationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AgentGroupDelegationUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if agentgroupdelegation.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized agentgroupdelegation.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := agentgroupdelegation.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *AgentGroupDelegationUpdateOne) check() error {
	if _u.mutation.ManagerCleared() && len(_u.mutation.ManagerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AgentGroupDelegation.manager"`)
	}
	if _u.mutation.ChildCleared() && len(_u.mutation.ChildIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AgentGroupDelegation.child"`)
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AgentGroupDelegation.group"`)
	}
	return nil
}

func (_u *AgentGroupDelegationUpdateOne) sqlSave(ctx context.Context) (_node *AgentGroupDelegation, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(agentgroupdelegation.Table, agentgroupdelegation.Columns, sqlgraph.NewFieldSpec(agentgroupdelegation.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AgentGroupDelegation.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, agentgroupdelegation.FieldID)
		for _, f := range fields {
			if !agentgroupdelegation.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != agentgroupdelegation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(agentgroupdelegation.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(agentgroupdelegation.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(agentgroupdelegation.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RateMultiplier(); ok {
		_spec.SetField(agentgroupdelegation.FieldRateMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRateMultiplier(); ok {
		_spec.AddField(agentgroupdelegation.FieldRateMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CanDelegate(); ok {
		_spec.SetField(agentgroupdelegation.FieldCanDelegate, field.TypeBool, value)
	}
	if _u.mutation.ManagerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentgroupdelegation.ManagerTable,
			Columns: []string{agentgroupdelegation.ManagerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ManagerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentgroupdelegation.ManagerTable,
			Columns: []string{agentgroupdelegation.ManagerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChildCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentgroupdelegation.ChildTable,
			Columns: []string{agentgroupdelegation.ChildColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChildIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentgroupdelegation.ChildTable,
			Columns: []string{agentgroupdelegation.ChildColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentgroupdelegation.GroupTable,
			Columns: []string{agentgroupdelegation.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentgroupdelegation.GroupTable,
			Columns: []string{agentgroupdelegation.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &AgentGroupDelegation{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{agentgroupdelegation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
