// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/agentgroupdelegation"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// AgentGroupDelegationCreate is the builder for creating a AgentGroupDelegation entity.
type AgentGroupDelegationCreate struct {
	config
	mutation *AgentGroupDelegationMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *AgentGroupDelegationCreate) SetCreatedAt(v time.Time) *AgentGroupDelegationCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AgentGroupDelegationCreate) SetNillableCreatedAt(v *time.Time) *AgentGroupDelegationCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AgentGroupDelegationCreate) SetUpdatedAt(v time.Time) *AgentGroupDelegationCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AgentGroupDelegationCreate) SetNillableUpdatedAt(v *time.Time) *AgentGroupDelegationCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *AgentGroupDelegationCreate) SetDeletedAt(v time.Time) *AgentGroupDelegationCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *AgentGroupDelegationCreate) SetNillableDeletedAt(v *time.Time) *AgentGroupDelegationCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetManagerUserID sets the "manager_user_id" field.
func (_c *AgentGroupDelegationCreate) SetManagerUserID(v int64) *AgentGroupDelegationCreate {
	_c.mutation.SetManagerUserID(v)
	return _c
}

// SetChildUserID sets the "child_user_id" field.
func (_c *AgentGroupDelegationCreate) SetChildUserID(v int64) *AgentGroupDelegationCreate {
	_c.mutation.SetChildUserID(v)
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *AgentGroupDelegationCreate) SetGroupID(v int64) *AgentGroupDelegationCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetRateMultiplier sets the "rate_multiplier" field.
func (_c *AgentGroupDelegationCreate) SetRateMultiplier(v float64) *AgentGroupDelegationCreate {
	_c.mutation.SetRateMultiplier(v)
	return _c
}

// SetCanDelegate sets the "can_delegate" field.
func (_c *AgentGroupDelegationCreate) SetCanDelegate(v bool) *AgentGroupDelegationCreate {
	_c.mutation.SetCanDelegate(v)
	return _c
}

// SetNillableCanDelegate sets the "can_delegate" field if the given value is not nil.
func (_c *AgentGroupDelegationCreate) SetNillableCanDelegate(v *bool) *AgentGroupDelegationCreate {
	if v != nil {
		_c.SetCanDelegate(*v)
	}
	return _c
}

// SetManagerID sets the "manager" edge to the User entity by ID.
func (_c *AgentGroupDelegationCreate) SetManagerID(id int64) *AgentGroupDelegationCreate {
	_c.mutation.SetManagerID(id)
	return _c
}

// SetManager sets the "manager" edge to the User entity.
func (_c *AgentGroupDelegationCreate) SetManager(v *User) *AgentGroupDelegationCreate {
	return _c.SetManagerID(v.ID)
}

// SetChildID sets the "child" edge to the User entity by ID.
func (_c *AgentGroupDelegationCreate) SetChildID(id int64) *AgentGroupDelegationCreate {
	_c.mutation.SetChildID(id)
	return _c
}

// SetChild sets the "child" edge to the User entity.
func (_c *AgentGroupDelegationCreate) SetChild(v *User) *AgentGroupDelegationCreate {
	return _c.SetChildID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_c *AgentGroupDelegationCreate) SetGroup(v *Group) *AgentGroupDelegationCreate {
	return _c.SetGroupID(v.ID)
}

// Mutation returns the AgentGroupDelegationMutation object of the builder.
func (_c *AgentGroupDelegationCreate) Mutation() *AgentGroupDelegationMutation {
	return _c.mutation
}

// Save creates the AgentGroupDelegation in the database.
func (_c *AgentGroupDelegationCreate) Save(ctx context.Context) (*AgentGroupDelegation, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AgentGroupDelegationCreate) SaveX(ctx context.Context) *AgentGroupDelegation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AgentGroupDelegationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AgentGroupDelegationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AgentGroupDelegationCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if agentgroupdelegation.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized agentgroupdelegation.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := agentgroupdelegation.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if agentgroupdelegation.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized agentgroupdelegation.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := agentgroupdelegation.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.CanDelegate(); !ok {
		v := agentgroupdelegation.DefaultCanDelegate
		_c.mutation.SetCanDelegate(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *AgentGroupDelegationCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AgentGroupDelegation.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AgentGroupDelegation.updated_at"`)}
	}
	if _, ok := _c.mutation.ManagerUserID(); !ok {
		return &ValidationError{Name: "manager_user_id", err: errors.New(`ent: missing required field "AgentGroupDelegation.manager_user_id"`)}
	}
	if _, ok := _c.mutation.ChildUserID(); !ok {
		return &ValidationError{Name: "child_user_id", err: errors.New(`ent: missing required field "AgentGroupDelegation.child_user_id"`)}
	}
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "AgentGroupDelegation.group_id"`)}
	}
	if _, ok := _c.mutation.RateMultiplier(); !ok {
		return &ValidationError{Name: "rate_multiplier", err: errors.New(`ent: missing required field "AgentGroupDelegation.rate_multiplier"`)}
	}
	if _, ok := _c.mutation.CanDelegate(); !ok {
		return &ValidationError{Name: "can_delegate", err: errors.New(`ent: missing required field "AgentGroupDelegation.can_delegate"`)}
	}
	if len(_c.mutation.ManagerIDs()) == 0 {
		return &ValidationError{Name: "manager", err: errors.New(`ent: missing required edge "AgentGroupDelegation.manager"`)}
	}
	if len(_c.mutation.ChildIDs()) == 0 {
		return &ValidationError{Name: "child", err: errors.New(`ent: missing required edge "AgentGroupDelegation.child"`)}
	}
	if len(_c.mutation.GroupIDs()) == 0 {
		return &ValidationError{Name: "group", err: errors.New(`ent: missing required edge "AgentGroupDelegation.group"`)}
	}
	return nil
}

func (_c *AgentGroupDelegationCreate) sqlSave(ctx context.Context) (*AgentGroupDelegation, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AgentGroupDelegationCreate) createSpec() (*AgentGroupDelegation, *sqlgraph.CreateSpec) {
	var (
		_node = &AgentGroupDelegation{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(agentgroupdelegation.Table, sqlgraph.NewFieldSpec(agentgroupdelegation.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(agentgroupdelegation.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(agentgroupdelegation.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(agentgroupdelegation.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.RateMultiplier(); ok {
		_spec.SetField(agentgroupdelegation.FieldRateMultiplier, field.TypeFloat64, value)
		_node.RateMultiplier = value
	}
	if value, ok := _c.mutation.CanDelegate(); ok {
		_spec.SetField(agentgroupdelegation.FieldCanDelegate, field.TypeBool, value)
		_node.CanDelegate = value
	}
	if nodes := _c.mutation.ManagerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentgroupdelegation.ManagerTable,
			Columns: []string{agentgroupdelegation.ManagerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ManagerUserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ChildIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentgroupdelegation.ChildTable,
			Columns: []string{agentgroupdelegation.ChildColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ChildUserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentgroupdelegation.GroupTable,
			Columns: []string{agentgroupdelegation.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GroupID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AgentGroupDelegation.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AgentGroupDelegationUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AgentGroupDelegationCreate) OnConflict(opts ...sql.ConflictOption) *AgentGroupDelegationUpsertOne {
	_c.conflict = opts
	return &AgentGroupDelegationUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AgentGroupDelegation.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AgentGroupDelegationCreate) OnConflictColumns(columns ...string) *AgentGroupDelegationUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AgentGroupDelegationUpsertOne{
		create: _c,
	}
}

type (
	// AgentGroupDelegationUpsertOne is the builder for "upsert"-ing
	//  one AgentGroupDelegation node.
	AgentGroupDelegationUpsertOne struct {
		create *AgentGroupDelegationCreate
	}

	// AgentGroupDelegationUpsert is the "OnConflict" setter.
	AgentGroupDelegationUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *AgentGroupDelegationUpsert) SetUpdatedAt(v time.Time) *AgentGroupDelegationUpsert {
	u.Set(agentgroupdelegation.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AgentGroupDelegationUpsert) UpdateUpdatedAt() *AgentGroupDelegationUpsert {
	u.SetExcluded(agentgroupdelegation.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *AgentGroupDelegationUpsert) SetDeletedAt(v time.Time) *AgentGroupDelegationUpsert {
	u.Set(agentgroupdelegation.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *AgentGroupDelegationUpsert) UpdateDeletedAt() *AgentGroupDelegationUpsert {
	u.SetExcluded(agentgroupdelegation.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *AgentGroupDelegationUpsert) ClearDeletedAt() *AgentGroupDelegationUpsert {
	u.SetNull(agentgroupdelegation.FieldDeletedAt)
	return u
}

// SetManagerUserID sets the "manager_user_id" field.
func (u *AgentGroupDelegationUpsert) SetManagerUserID(v int64) *AgentGroupDelegationUpsert {
	u.Set(agentgroupdelegation.FieldManagerUserID, v)
	return u
}

// UpdateManagerUserID sets the "manager_user_id" field to the value that was provided on create.
func (u *AgentGroupDelegationUpsert) UpdateManagerUserID() *AgentGroupDelegationUpsert {
	u.SetExcluded(agentgroupdelegation.FieldManagerUserID)
	return u
}

// SetChildUserID sets the "child_user_id" field.
func (u *AgentGroupDelegationUpsert) SetChildUserID(v int64) *AgentGroupDelegationUpsert {
	u.Set(agentgroupdelegation.FieldChildUserID, v)
	return u
}

// UpdateChildUserID sets the "child_user_id" field to the value that was provided on create.
func (u *AgentGroupDelegationUpsert) UpdateChildUserID() *AgentGroupDelegationUpsert {
	u.SetExcluded(agentgroupdelegation.FieldChildUserID)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *AgentGroupDelegationUpsert) SetGroupID(v int64) *AgentGroupDelegationUpsert {
	u.Set(agentgroupdelegation.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *AgentGroupDelegationUpsert) UpdateGroupID() *AgentGroupDelegationUpsert {
	u.SetExcluded(agentgroupdelegation.FieldGroupID)
	return u
}

// SetRateMultiplier sets the "rate_multiplier" field.
func (u *AgentGroupDelegationUpsert) SetRateMultiplier(v float64) *AgentGroupDelegationUpsert {
	u.Set(agentgroupdelegation.FieldRateMultiplier, v)
	return u
}

// UpdateRateMultiplier sets the "rate_multiplier" field to the value that was provided on create.
func (u *AgentGroupDelegationUpsert) UpdateRateMultiplier() *AgentGroupDelegationUpsert {
	u.SetExcluded(agentgroupdelegation.FieldRateMultiplier)
	return u
}

// AddRateMultiplier adds v to the "rate_multiplier" field.
func (u *AgentGroupDelegationUpsert) AddRateMultiplier(v float64) *AgentGroupDelegationUpsert {
	u.Add(agentgroupdelegation.FieldRateMultiplier, v)
	return u
}

// SetCanDelegate sets the "can_delegate" field.
func (u *AgentGroupDelegationUpsert) SetCanDelegate(v bool) *AgentGroupDelegationUpsert {
	u.Set(agentgroupdelegation.FieldCanDelegate, v)
	return u
}

// UpdateCanDelegate sets the "can_delegate" field to the value that was provided on create.
func (u *AgentGroupDelegationUpsert) UpdateCanDelegate() *AgentGroupDelegationUpsert {
	u.SetExcluded(agentgroupdelegation.FieldCanDelegate)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.AgentGroupDelegation.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AgentGroupDelegationUpsertOne) UpdateNewValues() *AgentGroupDelegationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(agentgroupdelegation.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AgentGroupDelegation.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AgentGroupDelegationUpsertOne) Ignore() *AgentGroupDelegationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AgentGroupDelegationUpsertOne) DoNothing() *AgentGroupDelegationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AgentGroupDelegationCreate.OnConflict
// documentation for more info.
func (u *AgentGroupDelegationUpsertOne) Update(set func(*AgentGroupDelegationUpsert)) *AgentGroupDelegationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AgentGroupDelegationUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AgentGroupDelegationUpsertOne) SetUpdatedAt(v time.Time) *AgentGroupDelegationUpsertOne {
	return u.Update(func(s *AgentGroupDelegationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AgentGroupDelegationUpsertOne) UpdateUpdatedAt() *AgentGroupDelegationUpsertOne {
	return u.Update(func(s *AgentGroupDelegationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *AgentGroupDelegationUpsertOne) SetDeletedAt(v time.Time) *AgentGroupDelegationUpsertOne {
	return u.Update(func(s *AgentGroupDelegationUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *AgentGroupDelegationUpsertOne) UpdateDeletedAt() *AgentGroupDelegationUpsertOne {
	return u.Update(func(s *AgentGroupDelegationUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *AgentGroupDelegationUpsertOne) ClearDeletedAt() *AgentGroupDelegationUpsertOne {
	return u.Update(func(s *AgentGroupDelegationUpsert) {
		s.ClearDeletedAt()
	})
}

// SetManagerUserID sets the "manager_user_id" field.
func (u *AgentGroupDelegationUpsertOne) SetManagerUserID(v int64) *AgentGroupDelegationUpsertOne {
	return u.Update(func(s *AgentGroupDelegationUpsert) {
		s.SetManagerUserID(v)
	})
}

// UpdateManagerUserID sets the "manager_user_id" field to the value that was provided on create.
func (u *AgentGroupDelegationUpsertOne) UpdateManagerUserID() *AgentGroupDelegationUpsertOne {
	return u.Update(func(s *AgentGroupDelegationUpsert) {
		s.UpdateManagerUserID()
	})
}

// SetChildUserID sets the "child_user_id" field.
func (u *AgentGroupDelegationUpsertOne) SetChildUserID(v int64) *AgentGroupDelegationUpsertOne {
	return u.Update(func(s *AgentGroupDelegationUpsert) {
		s.SetChildUserID(v)
	})
}

// UpdateChildUserID sets the "child_user_id" field to the value that was provided on create.
func (u *AgentGroupDelegationUpsertOne) UpdateChildUserID() *AgentGroupDelegationUpsertOne {
	return u.Update(func(s *AgentGroupDelegationUpsert) {
		s.UpdateChildUserID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *AgentGroupDelegationUpsertOne) SetGroupID(v int64) *AgentGroupDelegationUpsertOne {
	return u.Update(func(s *AgentGroupDelegationUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *AgentGroupDelegationUpsertOne) UpdateGroupID() *AgentGroupDelegationUpsertOne {
	return u.Update(func(s *AgentGroupDelegationUpsert) {
		s.UpdateGroupID()
	})
}

// SetRateMultiplier sets the "rate_multiplier" field.
func (u *AgentGroupDelegationUpsertOne) SetRateMultiplier(v float64) *AgentGroupDelegationUpsertOne {
	return u.Update(func(s *AgentGroupDelegationUpsert) {
		s.SetRateMultiplier(v)
	})
}

// AddRateMultiplier adds v to the "rate_multiplier" field.
func (u *AgentGroupDelegationUpsertOne) AddRateMultiplier(v float64) *AgentGroupDelegationUpsertOne {
	return u.Update(func(s *AgentGroupDelegationUpsert) {
		s.AddRateMultiplier(v)
	})
}

// UpdateRateMultiplier sets the "rate_multiplier" field to the value that was provided on create.
func (u *AgentGroupDelegationUpsertOne) UpdateRateMultiplier() *AgentGroupDelegationUpsertOne {
	return u.Update(func(s *AgentGroupDelegationUpsert) {
		s.UpdateRateMultiplier()
	})
}

// SetCanDelegate sets the "can_delegate" field.
func (u *AgentGroupDelegationUpsertOne) SetCanDelegate(v bool) *AgentGroupDelegationUpsertOne {
	return u.Update(func(s *AgentGroupDelegationUpsert) {
		s.SetCanDelegate(v)
	})
}

// UpdateCanDelegate sets the "can_delegate" field to the value that was provided on create.
func (u *AgentGroupDelegationUpsertOne) UpdateCanDelegate() *AgentGroupDelegationUpsertOne {
	return u.Update(func(s *AgentGroupDelegationUpsert) {
		s.UpdateCanDelegate()
	})
}

// Exec executes the query.
func (u *AgentGroupDelegationUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AgentGroupDelegationCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AgentGroupDelegationUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AgentGroupDelegationUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AgentGroupDelegationUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AgentGroupDelegationCreateBulk is the builder for creating many AgentGroupDelegation entities in bulk.
type AgentGroupDelegationCreateBulk struct {
	config
	err      error
	builders []*AgentGroupDelegationCreate
	conflict []sql.ConflictOption
}

// Save creates the AgentGroupDelegation entities in the database.
func (_c *AgentGroupDelegationCreateBulk) Save(ctx context.Context) ([]*AgentGroupDelegation, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AgentGroupDelegation, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AgentGroupDelegationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AgentGroupDelegationCreateBulk) SaveX(ctx context.Context) []*AgentGroupDelegation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AgentGroupDelegationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AgentGroupDelegationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AgentGroupDelegation.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AgentGroupDelegationUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AgentGroupDelegationCreateBulk) OnConflict(opts ...sql.ConflictOption) *AgentGroupDelegationUpsertBulk {
	_c.conflict = opts
	return &AgentGroupDelegationUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AgentGroupDelegation.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AgentGroupDelegationCreateBulk) OnConflictColumns(columns ...string) *AgentGroupDelegationUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AgentGroupDelegationUpsertBulk{
		create: _c,
	}
}

// AgentGroupDelegationUpsertBulk is the builder for "upsert"-ing
// a bulk of AgentGroupDelegation nodes.
type AgentGroupDelegationUpsertBulk struct {
	create *AgentGroupDelegationCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AgentGroupDelegation.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AgentGroupDelegationUpsertBulk) UpdateNewValues() *AgentGroupDelegationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(agentgroupdelegation.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AgentGroupDelegation.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AgentGroupDelegationUpsertBulk) Ignore() *AgentGroupDelegationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AgentGroupDelegationUpsertBulk) DoNothing() *AgentGroupDelegationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AgentGroupDelegationCreateBulk.OnConflict
// documentation for more info.
func (u *AgentGroupDelegationUpsertBulk) Update(set func(*AgentGroupDelegationUpsert)) *AgentGroupDelegationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AgentGroupDelegationUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AgentGroupDelegationUpsertBulk) SetUpdatedAt(v time.Time) *AgentGroupDelegationUpsertBulk {
	return u.Update(func(s *AgentGroupDelegationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AgentGroupDelegationUpsertBulk) UpdateUpdatedAt() *AgentGroupDelegationUpsertBulk {
	return u.Update(func(s *AgentGroupDelegationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *AgentGroupDelegationUpsertBulk) SetDeletedAt(v time.Time) *AgentGroupDelegationUpsertBulk {
	return u.Update(func(s *AgentGroupDelegationUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *AgentGroupDelegationUpsertBulk) UpdateDeletedAt() *AgentGroupDelegationUpsertBulk {
	return u.Update(func(s *AgentGroupDelegationUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *AgentGroupDelegationUpsertBulk) ClearDeletedAt() *AgentGroupDelegationUpsertBulk {
	return u.Update(func(s *AgentGroupDelegationUpsert) {
		s.ClearDeletedAt()
	})
}

// SetManagerUserID sets the "manager_user_id" field.
func (u *AgentGroupDelegationUpsertBulk) SetManagerUserID(v int64) *AgentGroupDelegationUpsertBulk {
	return u.Update(func(s *AgentGroupDelegationUpsert) {
		s.SetManagerUserID(v)
	})
}

// UpdateManagerUserID sets the "manager_user_id" field to the value that was provided on create.
func (u *AgentGroupDelegationUpsertBulk) UpdateManagerUserID() *AgentGroupDelegationUpsertBulk {
	return u.Update(func(s *AgentGroupDelegationUpsert) {
		s.UpdateManagerUserID()
	})
}

// SetChildUserID sets the "child_user_id" field.
func (u *AgentGroupDelegationUpsertBulk) SetChildUserID(v int64) *AgentGroupDelegationUpsertBulk {
	return u.Update(func(s *AgentGroupDelegationUpsert) {
		s.SetChildUserID(v)
	})
}

// UpdateChildUserID sets the "child_user_id" field to the value that was provided on create.
func (u *AgentGroupDelegationUpsertBulk) UpdateChildUserID() *AgentGroupDelegationUpsertBulk {
	return u.Update(func(s *AgentGroupDelegationUpsert) {
		s.UpdateChildUserID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *AgentGroupDelegationUpsertBulk) SetGroupID(v int64) *AgentGroupDelegationUpsertBulk {
	return u.Update(func(s *AgentGroupDelegationUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *AgentGroupDelegationUpsertBulk) UpdateGroupID() *AgentGroupDelegationUpsertBulk {
	return u.Update(func(s *AgentGroupDelegationUpsert) {
		s.UpdateGroupID()
	})
}

// SetRateMultiplier sets the "rate_multiplier" field.
func (u *AgentGroupDelegationUpsertBulk) SetRateMultiplier(v float64) *AgentGroupDelegationUpsertBulk {
	return u.Update(func(s *AgentGroupDelegationUpsert) {
		s.SetRateMultiplier(v)
	})
}

// AddRateMultiplier adds v to the "rate_multiplier" field.
func (u *AgentGroupDelegationUpsertBulk) AddRateMultiplier(v float64) *AgentGroupDelegationUpsertBulk {
	return u.Update(func(s *AgentGroupDelegationUpsert) {
		s.AddRateMultiplier(v)
	})
}

// UpdateRateMultiplier sets the "rate_multiplier" field to the value that was provided on create.
func (u *AgentGroupDelegationUpsertBulk) UpdateRateMultiplier() *AgentGroupDelegationUpsertBulk {
	return u.Update(func(s *AgentGroupDelegationUpsert) {
		s.UpdateRateMultiplier()
	})
}

// SetCanDelegate sets the "can_delegate" field.
func (u *AgentGroupDelegationUpsertBulk) SetCanDelegate(v bool) *AgentGroupDelegationUpsertBulk {
	return u.Update(func(s *AgentGroupDelegationUpsert) {
		s.SetCanDelegate(v)
	})
}

// UpdateCanDelegate sets the "can_delegate" field to the value that was provided on create.
func (u *AgentGroupDelegationUpsertBulk) UpdateCanDelegate() *AgentGroupDelegationUpsertBulk {
	return u.Update(func(s *AgentGroupDelegationUpsert) {
		s.UpdateCanDelegate()
	})
}

// Exec executes the query.
func (u *AgentGroupDelegationUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AgentGroupDelegationCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AgentGroupDelegationCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AgentGroupDelegationUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
