// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/agentgroupdelegation"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// AgentGroupDelegationDelete is the builder for deleting a AgentGroupDelegation entity.
type AgentGroupDelegationDelete struct {
	config
	hooks    []Hook
	mutation *AgentGroupDelegationMutation
}

// Where appends a list predicates to the AgentGroupDelegationDelete builder.
func (_d *AgentGroupDelegationDelete) Where(ps ...predicate.AgentGroupDelegation) *AgentGroupDelegationDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *AgentGroupDelegationDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AgentGroupDelegationDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *AgentGroupDelegationDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(agentgroupdelegation.Table, sqlgraph.NewFieldSpec(agentgroupdelegation.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// AgentGroupDelegationDeleteOne is the builder for deleting a single AgentGroupDelegation entity.
type AgentGroupDelegationDeleteOne struct {
	_d *AgentGroupDelegationDelete
}

// Where appends a list predicates to the AgentGroupDelegationDelete builder.
func (_d *AgentGroupDelegationDeleteOne) Where(ps ...predicate.AgentGroupDelegation) *AgentGroupDelegationDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *AgentGroupDelegationDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{agentgroupdelegation.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AgentGroupDelegationDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
