// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/agentgroupdelegation"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// AgentGroupDelegation is the model entity for the AgentGroupDelegation schema.
type AgentGroupDelegation struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// ManagerUserID holds the value of the "manager_user_id" field.
	ManagerUserID int64 `json:"manager_user_id,omitempty"`
	// ChildUserID holds the value of the "child_user_id" field.
	ChildUserID int64 `json:"child_user_id,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID int64 `json:"group_id,omitempty"`
	// RateMultiplier holds the value of the "rate_multiplier" field.
	RateMultiplier float64 `json:"rate_multiplier,omitempty"`
	// CanDelegate holds the value of the "can_delegate" field.
	CanDelegate bool `json:"can_delegate,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AgentGroupDelegationQuery when eager-loading is set.
	Edges        AgentGroupDelegationEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AgentGroupDelegationEdges holds the relations/edges for other nodes in the graph.
type AgentGroupDelegationEdges struct {
	// Manager holds the value of the manager edge.
	Manager *User `json:"manager,omitempty"`
	// Child holds the value of the child edge.
	Child *User `json:"child,omitempty"`
	// Group holds the value of the group edge.
	Group *Group `json:"group,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// ManagerOrErr returns the Manager value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AgentGroupDelegationEdges) ManagerOrErr() (*User, error) {
	if e.Manager != nil {
		return e.Manager, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "manager"}
}

// ChildOrErr returns the Child value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AgentGroupDelegationEdges) ChildOrErr() (*User, error) {
	if e.Child != nil {
		return e.Child, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "child"}
}

// GroupOrErr returns the Group value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AgentGroupDelegationEdges) GroupOrErr() (*Group, error) {
	if e.Group != nil {
		return e.Group, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: group.Label}
	}
	return nil, &NotLoadedError{edge: "group"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AgentGroupDelegation) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case agentgroupdelegation.FieldCanDelegate:
			values[i] = new(sql.NullBool)
		case agentgroupdelegation.FieldRateMultiplier:
			values[i] = new(sql.NullFloat64)
		case agentgroupdelegation.FieldID, agentgroupdelegation.FieldManagerUserID, agentgroupdelegation.FieldChildUserID, agentgroupdelegation.FieldGroupID:
			values[i] = new(sql.NullInt64)
		case agentgroupdelegation.FieldCreatedAt, agentgroupdelegation.FieldUpdatedAt, agentgroupdelegation.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AgentGroupDelegation fields.
func (_m *AgentGroupDelegation) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case agentgroupdelegation.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case agentgroupdelegation.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case agentgroupdelegation.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case agentgroupdelegation.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case agentgroupdelegation.FieldManagerUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field manager_user_id", values[i])
			} else if value.Valid {
				_m.ManagerUserID = value.Int64
			}
		case agentgroupdelegation.FieldChildUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field child_user_id", values[i])
			} else if value.Valid {
				_m.ChildUserID = value.Int64
			}
		case agentgroupdelegation.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = value.Int64
			}
		case agentgroupdelegation.FieldRateMultiplier:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field rate_multiplier", values[i])
			} else if value.Valid {
				_m.RateMultiplier = value.Float64
			}
		case agentgroupdelegation.FieldCanDelegate:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field can_delegate", values[i])
			} else if value.Valid {
				_m.CanDelegate = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AgentGroupDelegation.
// This includes values selected through modifiers, order, etc.
func (_m *AgentGroupDelegation) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryManager queries the "manager" edge of the AgentGroupDelegation entity.
func (_m *AgentGroupDelegation) QueryManager() *UserQuery {
	return NewAgentGroupDelegationClient(_m.config).QueryManager(_m)
}

// QueryChild queries the "child" edge of the AgentGroupDelegation entity.
func (_m *AgentGroupDelegation) QueryChild() *UserQuery {
	return NewAgentGroupDelegationClient(_m.config).QueryChild(_m)
}

// QueryGroup queries the "group" edge of the AgentGroupDelegation entity.
func (_m *AgentGroupDelegation) QueryGroup() *GroupQuery {
	return NewAgentGroupDelegationClient(_m.config).QueryGroup(_m)
}

// Update returns a builder for updating this AgentGroupDelegation.
// Note that you need to call AgentGroupDelegation.Unwrap() before calling this method if this AgentGroupDelegation
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AgentGroupDelegation) Update() *AgentGroupDelegationUpdateOne {
	return NewAgentGroupDelegationClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AgentGroupDelegation entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AgentGroupDelegation) Unwrap() *AgentGroupDelegation {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AgentGroupDelegation is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AgentGroupDelegation) String() string {
	var builder strings.Builder
	builder.WriteString("AgentGroupDelegation(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("manager_user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ManagerUserID))
	builder.WriteString(", ")
	builder.WriteString("child_user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ChildUserID))
	builder.WriteString(", ")
	builder.WriteString("group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupID))
	builder.WriteString(", ")
	builder.WriteString("rate_multiplier=")
	builder.WriteString(fmt.Sprintf("%v", _m.RateMultiplier))
	builder.WriteString(", ")
	builder.WriteString("can_delegate=")
	builder.WriteString(fmt.Sprintf("%v", _m.CanDelegate))
	builder.WriteByte(')')
	return builder.String()
}

// AgentGroupDelegations is a parsable slice of AgentGroupDelegation.
type AgentGroupDelegations []*AgentGroupDelegation
