// Code generated by ent, DO NOT EDIT.

package agentgroupdelegation

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.AgentGroupDelegation {
	return predicate.AgentGroupDelegation(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.AgentGroupDelegation {
	return predicate.AgentGroupDelegation(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.AgentGroupDelegation {
	return predicate.AgentGroupDelegation(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.AgentGroupDelegation {
	return predicate.AgentGroupDelegation(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.AgentGroupDelegation {
	return predicate.AgentGroupDelegation(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.AgentGroupDelegation {
	return predicate.AgentGroupDelegation(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.AgentGroupDelegation {
	return predicate.AgentGroupDelegation(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.AgentGroupDelegation {
	return predicate.AgentGroupDelegation(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.AgentGroupDelegation {
	return predicate.AgentGroupDelegation(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AgentGroupDelegation {
	return predicate.AgentGroupDelegation(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AgentGroupDelegation {
	return predicate.AgentGroupDelegation(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.AgentGroupDelegation {
	return predicate.AgentGroupDelegation(sql.FieldEQ(FieldDeletedAt, v))
}

// ManagerUserID applies equality check predicate on the "manager_user_id" field. It's identical to ManagerUserIDEQ.
func ManagerUserID(v int64) predicate.AgentGroupDelegation {
	return predicate.AgentGroupDelegation(sql.FieldEQ(FieldManagerUserID, v))
}

// ChildUserID applies equality check predicate on the "child_user_id" field. It's identical to ChildUserIDEQ.
func ChildUserID(v int64) predicate.AgentGroupDelegation {
	return predicate.AgentGroupDelegation(sql.FieldEQ(FieldChildUserID, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.AgentGroupDelegation {
	return predicate.AgentGroupDelegation(sql.FieldEQ(FieldGroupID, v))
}

// RateMultiplier applies equality check predicate on the "rate_multiplier" field. It's identical to RateMultiplierEQ.
func RateMultiplier(v float64) predicate.AgentGroupDelegation {
	return predicate.AgentGroupDelegation(sql.FieldEQ(FieldRateMultiplier, v))
}

// CanDelegate applies equality check predicate on the "can_delegate" field. It's identical to CanDelegateEQ.
func CanDelegate(v bool) predicate.AgentGroupDelegation {
	return predicate.AgentGroupDelegation(sql.FieldEQ(FieldCanDelegate, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AgentGroupDelegation {
	return predicate.AgentGroupDelegation(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AgentGroupDelegation {
	return predicate.AgentGroupDelegation(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AgentGroupDelegation {
	return predicate.AgentGroupDelegation(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AgentGroupDelegation {
	return predicate.AgentGroupDelegation(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AgentGroupDelegation {
	return predicate.AgentGroupDelegation(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AgentGroupDelegation {
	return predicate.AgentGroupDelegation(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AgentGroupDelegation {
	return predicate.AgentGroupDelegation(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AgentGroupDelegation {
	return predicate.AgentGroupDelegation(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AgentGroupDelegation {
	return predicate.AgentGroupDelegation(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AgentGroupDelegation {
	return predicate.AgentGroupDelegation(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AgentGroupDelegation {
	return predicate.AgentGroupDelegation(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AgentGroupDelegation {
	return predicate.AgentGroupDelegation(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AgentGroupDelegation {
	return predicate.AgentGroupDelegation(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AgentGroupDelegation {
	return predicate.AgentGroupDelegation(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AgentGroupDelegation {
	return predicate.AgentGroupDelegation(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AgentGroupDelegation {
	return predicate.AgentGroupDelegation(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.AgentGroupDelegation {
	return predicate.AgentGroupDelegation(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.AgentGroupDelegation {
	return predicate.AgentGroupDelegation(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.AgentGroupDelegation {
	return predicate.AgentGroupDelegation(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.AgentGroupDelegation {
	return predicate.AgentGroupDelegation(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.AgentGroupDelegation {
	return predicate.AgentGroupDelegation(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.AgentGroupDelegation {
	return predicate.AgentGroupDelegation(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.AgentGroupDelegation {
	return predicate.AgentGroupDelegation(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.AgentGroupDelegation {
	return predicate.AgentGroupDelegation(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.AgentGroupDelegation {
	return predicate.AgentGroupDelegation(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.AgentGroupDelegation {
	return predicate.AgentGroupDelegation(sql.FieldNotNull(FieldDeletedAt))
}

// ManagerUserIDEQ applies the EQ predicate on the "manager_user_id" field.
func ManagerUserIDEQ(v int64) predicate.AgentGroupDelegation {
	return predicate.AgentGroupDelegation(sql.FieldEQ(FieldManagerUserID, v))
}

// ManagerUserIDNEQ applies the NEQ predicate on the "manager_user_id" field.
func ManagerUserIDNEQ(v int64) predicate.AgentGroupDelegation {
	return predicate.AgentGroupDelegation(sql.FieldNEQ(FieldManagerUserID, v))
}

// ManagerUserIDIn applies the In predicate on the "manager_user_id" field.
func ManagerUserIDIn(vs ...int64) predicate.AgentGroupDelegation {
	return predicate.AgentGroupDelegation(sql.FieldIn(FieldManagerUserID, vs...))
}

// ManagerUserIDNotIn applies the NotIn predicate on the "manager_user_id" field.
func ManagerUserIDNotIn(vs ...int64) predicate.AgentGroupDelegation {
	return predicate.AgentGroupDelegation(sql.FieldNotIn(FieldManagerUserID, vs...))
}

// ChildUserIDEQ applies the EQ predicate on the "child_user_id" field.
func ChildUserIDEQ(v int64) predicate.AgentGroupDelegation {
	return predicate.AgentGroupDelegation(sql.FieldEQ(FieldChildUserID, v))
}

// ChildUserIDNEQ applies the NEQ predicate on the "child_user_id" field.
func ChildUserIDNEQ(v int64) predicate.AgentGroupDelegation {
	return predicate.AgentGroupDelegation(sql.FieldNEQ(FieldChildUserID, v))
}

// ChildUserIDIn applies the In predicate on the "child_user_id" field.
func ChildUserIDIn(vs ...int64) predicate.AgentGroupDelegation {
	return predicate.AgentGroupDelegation(sql.FieldIn(FieldChildUserID, vs...))
}

// ChildUserIDNotIn applies the NotIn predicate on the "child_user_id" field.
func ChildUserIDNotIn(vs ...int64) predicate.AgentGroupDelegation {
	return predicate.AgentGroupDelegation(sql.FieldNotIn(FieldChildUserID, vs...))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.AgentGroupDelegation {
	return predicate.AgentGroupDelegation(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.AgentGroupDelegation {
	return predicate.AgentGroupDelegation(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.AgentGroupDelegation {
	return predicate.AgentGroupDelegation(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.AgentGroupDelegation {
	return predicate.AgentGroupDelegation(sql.FieldNotIn(FieldGroupID, vs...))
}

// RateMultiplierEQ applies the EQ predicate on the "rate_multiplier" field.
func RateMultiplierEQ(v float64) predicate.AgentGroupDelegation {
	return predicate.AgentGroupDelegation(sql.FieldEQ(FieldRateMultiplier, v))
}

// RateMultiplierNEQ applies the NEQ predicate on the "rate_multiplier" field.
func RateMultiplierNEQ(v float64) predicate.AgentGroupDelegation {
	return predicate.AgentGroupDelegation(sql.FieldNEQ(FieldRateMultiplier, v))
}

// RateMultiplierIn applies the In predicate on the "rate_multiplier" field.
func RateMultiplierIn(vs ...float64) predicate.AgentGroupDelegation {
	return predicate.AgentGroupDelegation(sql.FieldIn(FieldRateMultiplier, vs...))
}

// RateMultiplierNotIn applies the NotIn predicate on the "rate_multiplier" field.
func RateMultiplierNotIn(vs ...float64) predicate.AgentGroupDelegation {
	return predicate.AgentGroupDelegation(sql.FieldNotIn(FieldRateMultiplier, vs...))
}

// RateMultiplierGT applies the GT predicate on the "rate_multiplier" field.
func RateMultiplierGT(v float64) predicate.AgentGroupDelegation {
	return predicate.AgentGroupDelegation(sql.FieldGT(FieldRateMultiplier, v))
}

// RateMultiplierGTE applies the GTE predicate on the "rate_multiplier" field.
func RateMultiplierGTE(v float64) predicate.AgentGroupDelegation {
	return predicate.AgentGroupDelegation(sql.FieldGTE(FieldRateMultiplier, v))
}

// RateMultiplierLT applies the LT predicate on the "rate_multiplier" field.
func RateMultiplierLT(v float64) predicate.AgentGroupDelegation {
	return predicate.AgentGroupDelegation(sql.FieldLT(FieldRateMultiplier, v))
}

// RateMultiplierLTE applies the LTE predicate on the "rate_multiplier" field.
func RateMultiplierLTE(v float64) predicate.AgentGroupDelegation {
	return predicate.AgentGroupDelegation(sql.FieldLTE(FieldRateMultiplier, v))
}

// CanDelegateEQ applies the EQ predicate on the "can_delegate" field.
func CanDelegateEQ(v bool) predicate.AgentGroupDelegation {
	return predicate.AgentGroupDelegation(sql.FieldEQ(FieldCanDelegate, v))
}

// CanDelegateNEQ applies the NEQ predicate on the "can_delegate" field.
func CanDelegateNEQ(v bool) predicate.AgentGroupDelegation {
	return predicate.AgentGroupDelegation(sql.FieldNEQ(FieldCanDelegate, v))
}

// HasManager applies the HasEdge predicate on the "manager" edge.
func HasManager() predicate.AgentGroupDelegation {
	return predicate.AgentGroupDelegation(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ManagerTable, ManagerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasManagerWith applies the HasEdge predicate on the "manager" edge with a given conditions (other predicates).
func HasManagerWith(preds ...predicate.User) predicate.AgentGroupDelegation {
	return predicate.AgentGroupDelegation(func(s *sql.Selector) {
		step := newManagerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasChild applies the HasEdge predicate on the "child" edge.
func HasChild() predicate.AgentGroupDelegation {
	return predicate.AgentGroupDelegation(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ChildTable, ChildColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasChildWith applies the HasEdge predicate on the "child" edge with a given conditions (other predicates).
func HasChildWith(preds ...predicate.User) predicate.AgentGroupDelegation {
	return predicate.AgentGroupDelegation(func(s *sql.Selector) {
		step := newChildStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasGroup applies the HasEdge predicate on the "group" edge.
func HasGroup() predicate.AgentGroupDelegation {
	return predicate.AgentGroupDelegation(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, GroupTable, GroupColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGroupWith applies the HasEdge predicate on the "group" edge with a given conditions (other predicates).
func HasGroupWith(preds ...predicate.Group) predicate.AgentGroupDelegation {
	return predicate.AgentGroupDelegation(func(s *sql.Selector) {
		step := newGroupStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AgentGroupDelegation) predicate.AgentGroupDelegation {
	return predicate.AgentGroupDelegation(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AgentGroupDelegation) predicate.AgentGroupDelegation {
	return predicate.AgentGroupDelegation(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AgentGroupDelegation) predicate.AgentGroupDelegation {
	return predicate.AgentGroupDelegation(sql.NotPredicates(p))
}
